TREE = lib/Bio/Parse/Format
DIRS = BLAST1 BLAST2 BLAST2_OF7 FASTA1 FASTA2 FASTA3 FASTA3X FASTA2_GCG
FILE =
EXES =
SRCS = BLAST.pm      \
       BLAST1.pm     \
       BLAST2.pm     \
       BLAST2_OF7.pm \
       CLUSTAL.pm    \
       FASTA.pm      \
       FASTA1.pm     \
       FASTA2.pm     \
       FASTA2_GCG.pm \
       FASTA3.pm     \
       FASTA3X.pm    \
       HSSP.pm       \
       JNETZ.pm      \
       MAF.pm        \
       MIPS.pm       \
       MSF.pm        \
       MULTAS.pm     \
       PIR.pm        \
       Pearson.pm    \
       Plain.pm      \

HTML =

include $(HOME)/etc/MAKEFILE.templ
