TREE = lib/Bio/MView/Align
DIRS =
FILE =
EXES =
SRCS = Alignment.pm ColorMixin.pm Consensus.pm Conservation.pm Row.pm \
       Ruler.pm Sequence.pm Special.pm
HTML =

include $(HOME)/etc/MAKEFILE.templ
