TREE = lib/NPB/Parse/Format
DIRS = BLAST1 BLAST2 BLAST2_OF7 FASTA1 FASTA2 FASTA3 FASTA3X GCG_FASTA2
FILE =
EXES =
SRCS = BLAST.pm		\
       BLAST1.pm	\
       BLAST2.pm	\
       BLAST2_OF7.pm	\
       CLUSTAL.pm	\
       FASTA.pm		\
       FASTA1.pm	\
       FASTA2.pm	\
       FASTA3.pm	\
       FASTA3X.pm	\
       GCG_FASTA2.pm	\
       HSSP.pm		\
       JNETZ.pm		\
       MAF.pm		\
       MIPS.pm		\
       MSF.pm		\
       MULTAS.pm	\
       PIR.pm		\
       Pearson.pm	\
       Plain.pm		\
       Slurp.pm		\

HTML = 

include $(HOME)/etc/MAKEFILE.templ
