TREE = lib/Bio/Parse/Format/FASTA3X
DIRS =
FILE =
EXES =
SRCS = fasta.pm fastx.pm tfasta.pm \
       ssearch.pm ggsearch.pm glsearch.pm \
       fastm.pm tfastm.pm
HTML =

include $(HOME)/etc/MAKEFILE.templ
